//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thea_Travel.Ressources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thea_Travel.Ressources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresses utiles.
        /// </summary>
        internal static string AddrButton {
            get {
                return ResourceManager.GetString("AddrButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        internal static string CoButton {
            get {
                return ResourceManager.GetString("CoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deconnexion.
        /// </summary>
        internal static string DecoButton {
            get {
                return ResourceManager.GetString("DecoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feuilles de route.
        /// </summary>
        internal static string FdrButton {
            get {
                return ResourceManager.GetString("FdrButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du:.
        /// </summary>
        internal static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réessayer.
        /// </summary>
        internal static string IdIncoButton {
            get {
                return ResourceManager.GetString("IdIncoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réessayer.
        /// </summary>
        internal static string IdIncoOffButton {
            get {
                return ResourceManager.GetString("IdIncoOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afin de pouvoir utiliser le mode hors-ligne, merci d&apos;utiliser les mêmes identifiants que lors de votre dernière synchronisation..
        /// </summary>
        internal static string IdIncoOffText {
            get {
                return ResourceManager.GetString("IdIncoOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur d&apos;identification.
        /// </summary>
        internal static string IdIncoOffTitle {
            get {
                return ResourceManager.GetString("IdIncoOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe ou nom d&apos;utilisateur incorrect.
        /// </summary>
        internal static string IdIncoText {
            get {
                return ResourceManager.GetString("IdIncoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur d&apos;identification.
        /// </summary>
        internal static string IdIncoTitle {
            get {
                return ResourceManager.GetString("IdIncoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string InfoButton {
            get {
                return ResourceManager.GetString("InfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode hors-ligne.
        /// </summary>
        internal static string NoCoFirstButton {
            get {
                return ResourceManager.GetString("NoCoFirstButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réessayer.
        /// </summary>
        internal static string NoCoSecondButton {
            get {
                return ResourceManager.GetString("NoCoSecondButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifiez votre connection et réessayez ou bien continuez en mode hors ligne.
        /// </summary>
        internal static string NoCoText {
            get {
                return ResourceManager.GetString("NoCoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème de connexion.
        /// </summary>
        internal static string NoCoTitle {
            get {
                return ResourceManager.GetString("NoCoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom:.
        /// </summary>
        internal static string NomHotelLabel {
            get {
                return ResourceManager.GetString("NomHotelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        internal static string NoSyncButton {
            get {
                return ResourceManager.GetString("NoSyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune donnée synchronisée, veuillez vous connectez à internet et vous authentifiez afin de récupérer les données depuis le serveur. Vous pourrez ensuite utiliser le mode hors-ligne..
        /// </summary>
        internal static string NoSyncText {
            get {
                return ResourceManager.GetString("NoSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string NoSyncTitle {
            get {
                return ResourceManager.GetString("NoSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        internal static string PwdPlaceHolder {
            get {
                return ResourceManager.GetString("PwdPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ReqTimeOutButton {
            get {
                return ResourceManager.GetString("ReqTimeOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre connexion est trop lente.
        /// </summary>
        internal static string ReqTimeOutText {
            get {
                return ResourceManager.GetString("ReqTimeOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème de connexion.
        /// </summary>
        internal static string ReqTimeOutTitle {
            get {
                return ResourceManager.GetString("ReqTimeOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rester connecté.
        /// </summary>
        internal static string SwitchText {
            get {
                return ResourceManager.GetString("SwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tél:.
        /// </summary>
        internal static string TelHotelLabel {
            get {
                return ResourceManager.GetString("TelHotelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au:.
        /// </summary>
        internal static string ToLabel {
            get {
                return ResourceManager.GetString("ToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        internal static string UsrPlaceHolder {
            get {
                return ResourceManager.GetString("UsrPlaceHolder", resourceCulture);
            }
        }
    }
}
